# Generated by Django 3.2.7 on 2022-02-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_autores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'autores'},
        ),
    ]
