# Generated by Django 3.2.7 on 2022-02-20 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_itenscompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenscompra',
            old_name='quntidade',
            new_name='quantidade',
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
